[default]

machines = [
    "abc1234"
]

[default.databases]
postgres_db = { url = "postgres://vicky:vicky@localhost/vicky" }

[default.s3_config]
endpoint = "http://localhost:9000"
access_key_id = "minio"
secret_access_key = "aichudiKohr6aithi4ahh3aeng2eL7xo"
region = "us-east-1"
log_bucket = "vicky-logs"
force_path_style = false

[default.oidc_config]
well_known_uri = ""

[default.web_config]
authority = ""
client_id = "vicky-dev"
